// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrtyMyKxZv68wWet209EQl2qe58IWWDDU',
    appId: '1:191162173668:web:c510783fa44f3ec144c4f1',
    messagingSenderId: '191162173668',
    projectId: 'this-is-nigeria-9db35',
    authDomain: 'this-is-nigeria-9db35.firebaseapp.com',
    storageBucket: 'this-is-nigeria-9db35.appspot.com',
    measurementId: 'G-LR42H5033L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBglv0JxByG0ZX3rUKv8wq94ucFAcFb3V4',
    appId: '1:191162173668:android:cf9270f6ed9c806244c4f1',
    messagingSenderId: '191162173668',
    projectId: 'this-is-nigeria-9db35',
    storageBucket: 'this-is-nigeria-9db35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLnp6cdWVF8EuM_ex3AGNp86BZp6noyNA',
    appId: '1:191162173668:ios:030be90bfd574ea344c4f1',
    messagingSenderId: '191162173668',
    projectId: 'this-is-nigeria-9db35',
    storageBucket: 'this-is-nigeria-9db35.appspot.com',
    iosClientId: '191162173668-tqvs90r7la62ga01vh3ucduiu0gdm0v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.thisIsNigeria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLnp6cdWVF8EuM_ex3AGNp86BZp6noyNA',
    appId: '1:191162173668:ios:030be90bfd574ea344c4f1',
    messagingSenderId: '191162173668',
    projectId: 'this-is-nigeria-9db35',
    storageBucket: 'this-is-nigeria-9db35.appspot.com',
    iosClientId: '191162173668-tqvs90r7la62ga01vh3ucduiu0gdm0v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.thisIsNigeria',
  );
}
